### PR TITLE
Add username tab completion

### PR DESCRIPTION
**Pull request by nforro**
This pull request adds tab completion on `@` character. It cycles through the list of matching usernames, Twitch style (or so I believe, it's been a while since I last used Twitch).
The list of usernames is taken from the current message history. That should be good enough for most purposes, I think.

I'm opening this as a draft to collect feedback. I'm not sure if there isn't a better way to pass the list of messages, for example.

### CODE REVIEW

**Comment by gabek** [comment]
This is awesome, thanks for sending it along!

I agree that the chat history is good enough for this purpose.

Some thoughts I had off the top of my head:

Instead of the messaging interface reducing the messages to usernames at the time they try to auto-complete, would it make sense to keep a list of usernames and debounce update it when messages come in?  Then the `app` can pass those usernames to `messaging`, without `messaging` having to reach back into the vue app.  This could also allow for something like displaying the number of people who are chatting, or even a userlist if we ever wanted either of those things (not something we need right now, though).

I'd love to hear what @gingervitis thinks.

**Comment by gingervitis** [comment]
With what the current messaging setup looks like, I think the more straight forward way to do this would be to do something like-

Within the `MessagingInterface` class we could capture all the author names into a local array from the newMessages in the `onReceivedMessages()` method, so we don't have to parse through the message list at the vueApp level and reduce it every time we type.   

We can gather all the possible names from _all_ the newMessages when the app first loads, then on every subsequent message that comes in, we can just look for the author from the latest one.

**Comment by nforro** [comment]
Thanks for the suggestions, I've updated the commit.

**Comment by nforro** [comment]
Adn I added another commit that appears to resolve issue #100.

**Comment by gabek** [comment]
Awesome!

I see you're setting the class on the entire message if `isHighlighted`.  Do we want the entire message highlighted, or just the username?  I was experimenting with doing this in`formatText()` and just highlighting the username:

https://github.com/gabek/owncast/commit/ed8b4100bd2d1c5de5d8d3d88c684beb74f822e4#diff-9ef4ffb517508e5dbb07b9537d2b6fb8R38

I'd also prefer to not query the DOM to find the username, but I think the current username isn't available elsewhere right now.  I was thinking of passing it into `formatText()`.

I'll defer to what @gingervitis thinks :)

**Comment by nforro** [comment]
> Do we want the entire message highlighted, or just the username?

I'm fine with either. I did it this way because it seemed cleaner to me. Perhaps we could even do both?

> I was experimenting with doing this in`formatText()` and just highlighting the username:
> 
> [ed8b410#diff-9ef4ffb517508e5dbb07b9537d2b6fb8R38](https://github.com/gabek/owncast/commit/ed8b4100bd2d1c5de5d8d3d88c684beb74f822e4#diff-9ef4ffb517508e5dbb07b9537d2b6fb8R38)

Beware that this will match also parts of other words or other users' names (it's not that uncommon to have usernames where one is a substring of the other).

> I'd also prefer to not query the DOM to find the username

I don't like that any more than you do. There has to be a better way to do it, but I'm not familiar with *Vue.js* at all, so I'd be glad for pointers.

**Comment by gingervitis** [comment]
Yeah it makes sense to do the formatting in `formatText()`.

I'm not that familiar with Vuejs either, also not a fan of digging into the DOM. I'd also like to try and keep all the Messaging functionality related things within MessagingInterface if possible.

It may be worth moving the web socket functionality out of app.js and into MessagingInterface class instead, so everything is handled more locally there. (plus the web socket only seems to be used for messaging right now anyway). From there we can have more flexibility to manipulate the incoming messages and format them as needed.

We'll just have hack a way for the MessagingInterface class to go back out and update the vueApp.messages queue. :/

**Comment by gabek** [comment]
I'd like to split out the websocket into its own module that can be passed to other components, since it won't just be for messaging forever.  #48 is already on the table to use it for status updates, so it's best to split it out.

**Comment by gabek** [comment]
With regards to matching other parts of words with the username, I actually did that on purpose because I wanted to match things like "@name", "name:" "name," etc.  And since it's just highlighting it's no big deal unless you're somebody who makes their name the letter "a" or something dumb.

As for the username thing, I say we just go forward with the less than optimal solution of grabbing the value from the DOM and re-address it in any future web refactor.

So I vote that we just highlight the username, not the entire message, and if you do the highlighting in `formatText()`.

**Comment by gabek** [comment]
Just because it was mentioned in here, #104 was just merged in where Websocket is split out of the UI.  It shouldn't make a difference with this PR, but I wanted to bring it up anyway :)

**Comment by gabek** [comment]
It's working great!  I'll wait for @gingervitis to sign off on it, but it does what it says.

**Comment by gingervitis** [comment]
Works for me, thanks for working on this @nforro !

**Pull request merged**
