### PR TITLE
Transcoder updates for bitrate validator warnings 

### PR DESCRIPTION
**Pull request by gabek**
This change aims to fix the HLS validator warnings that arise due to spikes in bitrate and hopefully resolve the issue that #50 sees where it's dropping to the lower quality bitrate even when the higher one is perfectly fine.

### CODE REVIEW

**Comment by graywolf336** [comment]
Do you want me to use this branch tonight?

**Comment by gabek** [comment]
That would be great!  I don't think this is a silver bullet, but it should help if my guess of what might be happening is involved.

**Comment by gabek** [comment]
Ok, hopefully the state of that branch should keep the bitrate spikes at bay.   I'll run [mediastreamvalidator](https://developer.apple.com/documentation/http_live_streaming/about_apple_s_http_live_streaming_tools against your stream tonight and see what it has to say.

**Comment by gabek** [comment]
The good news is this fixes the HLS validator bitrate spike errors.  The bad news is it makes no difference with #50.  But hey, it's a net positive to keep players happy!  Merging it in.

**Pull request merged**
